### PR TITLE
Add getCompTox to Mbworkflow #215

### LINKED ISSUE #215: Add DTXSIDs into RMassBank identifiers
The EPA have preliminary webservices now available to retrieve DTXSIDs by InChIKey, we should add this into RMassBank to retrieve these for new records (and note that this may change again in the future)

https://github.com/MassBank/RMassBank/blob/master/R/webAccess.R

https://actorws.epa.gov/actorws/chemIdentifier/v01/resolve?identifier=IKHGUXGNUITLKF-UHFFFAOYSA-N 
https://actorws.epa.gov/actorws/chemIdentifier/v01/resolve.json?identifier=IKHGUXGNUITLKF-UHFFFAOYSA-N 
https://actorws.epa.gov/actorws/chemIdentifier/v01/resolve.xml?identifier=IKHGUXGNUITLKF-UHFFFAOYSA-N 

@adelenelai would you be interested in looking into this?

We are looking at doing this initially database side to get DTXSIDs into records already created: 
https://github.com/MassBank/MassBank-data/issues/66
and
https://github.com/MassBank/MassBank-web/issues/80

### PR DESCRIPTION
**Pull request by adelenelai**
getCompTox retrieves DTXSID from EPA webservices using InChiKey. Modify generation of infolists and of final Mbrecord to include DTXSID.
Resolves #215

### CODE REVIEW

**Comment by schymane** [comment]
@adelenelai please also note updated documentation / clarification re DSSTox webservices now included in https://github.com/MassBank/MassBank-data/issues/68 to avoid the unintentional inclusion of non-public data before the web services are fixed (=> results in broken links MassBank side)

**Comment by adelenelai** [comment]
Noted. Should not affect this present PR I think.

BTW, CI fails because of a Bioconductor issue, reported [here](https://travis-ci.community/t/error-bioconductor-version-not-changed/3491/2), but now apparently fixed. I need to restart the job/clear the cache somehow...?

**Comment by schymane** [comment]
It should be fixed their side too now so I agree, shouldn't affect this PR. Maybe @meier-rene or @Treutler or @sneumann or @meowcat can help re CI?

**Comment by sneumann** [comment]
Hi, triggering the CI now succeeded in https://travis-ci.org/MassBank/RMassBank/builds/538220884
(and, aha, also updated above). Both this PR and the other one (#228) suffer from a line-ending issue in `R/createMassBank.R` that we're investigating. Yours, Steffen

**Comment by sneumann** [comment]
Hi, I was too stupid to rebase the patch and merge conflicts. Hence I took your modifications 
and opened a new PR #229 . The commits are still attributed to you, so once the automatic checks 
have passed, this should be ready to be merged. Yours, Steffen

**Comment by sneumann** [comment]
Indeed, closing now in favour of #229. Yours, Steffen

**Pull request closed without merging**
