### PR TITLE
Devel

### PR DESCRIPTION
**Pull request by MaliRemorker**

### CODE REVIEW

**Comment by MaliRemorker** [comment]
Pulling in the parallel changes

**Comment by meowcat** [comment]
Hi,
looks nice; why did you close your pull request again?

**Comment by schymane** [comment]
We're still testing internally, it was a commit meant for the MaliRemorker branch not yet the official RMB one - are you happy to integrate when the time is right? We didn't want to interfere too much with S4power ...

**Comment by meowcat** [comment]
The msmsRead interface is not going to change with s4power. I like the idea of parallelization. I was actually thinking of parallelizing the analyze and reanalyze stuff (actually at very little expense we could directly do both in one step saving us a lot of time.)

I wonder whether we actually want a separate function. Look at the pattern in https://github.com/meowcat/RMassScreening/blob/master/R/batchPick.R where I handle both cases in the same function, would this be an option?

**Comment by schymane** [comment]
The parallelization has improved performance dramatically ... we're running thru changes in many places - also now having to merge CEs from different runs at the msmsRead stage to get enough data for recal ... (rather than originally later on just for multiplicity filtering). We can look into merging functions, if I understand @MaliRemorker is working off a very "abgespeckte" version and once we've tested it for bombproofness let's talk about integration. Keep an eye on his repo perhaps to see what's going on in the interim?

**Comment by meowcat** [comment]
Also, have you tested the performance? The peak picking in RMassScreening I use with up to 11 parallel threads, but that uses some weird readMzXml function, not the mzR backend (unless Martin changed it.) However the ProteoWizard guys claim that for raw to mzXML conversion, I/O becomes limiting pretty quickly if you use more than 2 threads. So I wonder where this one falls.

**Comment by meowcat** [comment]
> also now having to merge CEs from different runs at the msmsRead stage to get enough data for recal 

For this one, however, we should think more carefully at a good interface. I am actually also writing some changes (to extract EICs for all fragments, and use the EIC to filter out chemical noise a bit better) so we should try to not collide too much.

**Comment by schymane** [comment]
Yes, we are working on prescreening as well - but had not got far enough to look at EICs for fragments. There is definitely room to improve removal of noise up front using EICs so that we do not even process data for which no precursor is detected etc. Adding in fragment patterns would be even better. 
Sounds like we definitely need to coordinate at some point, for now we are still playing around as we are also not yet getting optimal data from the instruments.

**Comment by meowcat** [comment]
Are you talking about specific acquisition for library spectra, or the "semi-canonical" use for getting out spectra for a different masses from regular LC-MS sample acquisitions? Because if you want only high-quality features from regular samples, the XCMS reader workflow could be a possibility which should kind of already do that. (But it might be too strict, and I have zero experience with it.)

I mean, to only get to some degree the XCMS workflow already does that, no? Perhaps that cuts out too much stuff, however.

**Comment by MaliRemorker** [comment]
@meowcat first of all, sorry about the inadvertent PR, I shouldn't have been trying to merge stuff during a meeting. 

I created a new function since we're both users and "extenders-when-urgently-needed" of RMassBank. It was desirable to parallelise the No 1 bottleneck (reading through files compound-by-compound), but still be able to fall back to the standard way when things go wrong, or when we hit corner cases.

Also, I have focused only on mzR since this is what we mainly use atm, just that _that_ did not seem reasonable to be merged back to master as it is too specific. We could, though, use/create another branch on the official RMassBank where I can merge things as we go, provided you and @schymane think that makes sense. 

Regarding prescreening, our internal gitlab repo is very much in flux at the moment, but maybe it makes sense to go public. What do you think @schymane ?

**Comment by MaliRemorker** [comment]
Also, does it make sense to base work off S4 branch? How stable is that?

**Comment by meowcat** [comment]
It would at least be nice if active user-dev-people like you could already try it and see if it works for them, so I get complaints earlier rather than later. 

I am still backporting changes into the branch, and heavily suffering from not having decent regression tests in place, so I do a lot of running code, and then diffing by hand. But it now produces records that are (at least for some cases I tested) identical to the old ones.

Regarding your internal work, of course I have no idea what you are working on, but if you want a branch on the official repo at all, I warmly welcome it. I also was very happy to integrate @Treutler 's changes.

**Pull request closed without merging**
