### PR TITLE
Adding msp examples to RMassBank installation

### PR DESCRIPTION
**Pull request by pstahlhofen**
This adds example data and script for how to read msp data and feed them into the mbWorkflow. Some minor adjustments in the reading functions were made to simplify msp parsing.

### CODE REVIEW

**Review by sneumann — COMMENTED** [review]
I can confirm that the example script works as it should.

**Comment by meowcat** [comment]
Should the msp data (and potentially the final records) go to RMassBankData instead, or do we not care?

**Comment by sneumann** [comment]
Semantically they should go to RMassBankData, but then this is only a few KB ...

**Comment by meowcat** [comment]
I am moving them to RMassBankData. Any reason why the MSP files are called xxx.MSP.msp or can I change that?

**Comment by pstahlhofen** [comment]
If you do, you might have to change the Filelist as well.

**Pull request merged**
