### PR TITLE
Implemented log-wrapper

### PR DESCRIPTION
**Pull request by pstahlhofen**
This addresses #287
- Added logger-setting to RMassBank.env in zzz.R
- Implemented log_wrapper.R; Updated DESCRIPTION and NAMESPACE to include the logger package
- Updated documentation via Roxygen
- Added possibility to set the logging file by the user
- Updated documentation of RMB_settings in the vignette
- Replaced all calls to `message` by `log_info`

### CODE REVIEW

**Comment by pstahlhofen** [comment]
@tsufz @meowcat What do you think? If you like the current behaviour of the logger, I can extend its usage to other parts of `RMassBank`. Otherwise, I'd be happy about suggestions for improvements. To test this, reinstall `RMassBank` from the latest commit of this pr and run the `mbWorkflow`. If you want the logger to write to a file, set the `logging_file` in the settings.

**Comment by tsufz** [comment]
@pstahlhofen, I will check the code next week. I need to process some spectra anyway.

**Comment by meowcat** [comment]
I like it. However, could you change the `log_XXX` functions (which call the update_appender) to something like `rmb_log_XXX`? I don't think there's the need to "overwrite" the logger names, particularly when you export the functions. Or is there a rationale for that?

Also, I'm not sure that you should export the functions, but I'm not completely sure about this :)

**Comment by meowcat** [comment]
By the way, I found this https://github.com/daroczig/logger/blob/master/vignettes/r_packages.Rmd about logging from packages. Might be good to use this namespace thing.

**Comment by pstahlhofen** [comment]
@meowcat thanks for the hint. The namespace allowed me to drop the internal package variable and to remove the `update_appender` function.
Also, I did. the renaming as you suggested. I think the functions should remain exported so users can apply them for debugging

**Comment by pstahlhofen** [comment]
@tsufz @meowcat @schymane @sneumann
I will now merge the logger implementation as this pr has been open for almost two months now and it is blocking others from being merged. The reason I mentioned all of you here is because I replaced all calls to `message` in all scripts by calls to `rmb_log_info` and I would like you to use that function in the future instead of `message`.
@tsufz I checked #292 and it seems like you can easily resolve the merge conflict in the `DESCRIPTION` which will arise now by keeping both changes.
Note: So far, I only replaced calls to `message` to give us a test phase with the new logging system. If you like the behaviour, I'll make a second pr in the near future, replacing also calls to `cat`, `warning` etc. If something is odd, however, please let me know. I'm only merging into 'dev' so there's no harm done on BioConductor.

**Pull request merged**
