### PR TITLE
Fix #339

### LINKED ISSUE #339: Additional first column in infolist.csv
In the `infolist.csv` always occurs a first column without a column name. I guess this is an exporting artefact due to incorrect written export comments. It may be the index, written by "write.csv()". So, a factorisation to tidy commands is required.

### PR DESCRIPTION
**Pull request by tsufz**
Export and import replaced by readr versions.

### CODE REVIEW

**Comment by tsufz** [comment]
Sorry, fixes #339.

**Comment by meowcat** [comment]
hi,

1) great initiative to start with the refactoring!
2) I suggest to version at the fourth digit (`3.11.1.2`) for iterations in this repo, and to increase third digit only when pushing to Bioc... at least that's what I did. Other suggestions?
3) XCMS vignette fails now, it seems to have worked before. Any idea why?

**Comment by tsufz** [comment]
> hi,
> 
>     1. great initiative to start with the refactoring!
> 
>     2. I suggest to version at the fourth digit (`3.11.1.2`) for iterations in this repo, and to increase third digit only when pushing to Bioc... at least that's what I did. Other suggestions?
> 




> hi,
> 
>     1. great initiative to start with the refactoring!
> 
>     2. I suggest to version at the fourth digit (`3.11.1.2`) for iterations in this repo, and to increase third digit only when pushing to Bioc... at least that's what I did. Other suggestions?
> 
>     3. XCMS vignette fails now, it seems to have worked before. Any idea why?

1. Thanks, came by on WIP :-).
2. I am happy with this. I will change the version to `3.11.1.2` and push again.
3. I can check this locally, maybe I find a reason.

**Comment by tsufz** [comment]
I need to check the code anyway again, somehow NAs are imputed in the records.

```
COMMENT: INTERNAL_ID 4113
CH$NAME: 
CH$COMPOUND_CLASS: NA
CH$FORMULA: NA
CH$EXACT_MASS: NA
CH$SMILES: NA
CH$IUPAC: NA
```

**Comment by tsufz** [comment]
@meowcat, I guess that the downstream functions expecte a dataframe? But readr::read_csv imports a tibble(), hence, we need to transform the imported table?

**Comment by tsufz** [comment]
Well,  for whatever reason `loadinfolist` imputes now `NA` to the imported table. This is the cause for the downstream problems. Will figure this out tomorrow...

**Comment by tsufz** [comment]
@meowcat I guess, now is all okay, so read for review.

**Comment by tsufz** [comment]
Okay, normal workflow fails, checked locally, something with the infolists due to refacorisation. However, requires update of RMassBankData as soon it works locally. In meanwhile, we could use the github package for testing.

**Comment by tsufz** [comment]
> Okay, normal workflow fails, checked locally, something with the infolists due to refacorisation. However, requires update of RMassBankData as soon it works locally. In meanwhile, we could use the github package for testing.

@meowcat A sorry, the problem is that the BioC RMassBankData is not up-to-date (see latest [update ](https://github.com/MassBank/RMassBankData). I needed to change the data in the csvs to reflect changes in naming in RMassBank.

I suggested to change the source of RMassBank data package to the github main until my PR is running through and we can safely update the BioC package?

**Comment by meowcat** [comment]
Hm but in this case should we not provide the option to update old infolists? We are breaking backwards compatibility here. I would suggest that we keep "soft compatibility" by providing `updateInfolist` that rewrites the column name for old infolists.

**Comment by tsufz** [comment]
@meowcat, I agree with the breaking argument. But, I am looking forward. I suggest rewriting the infolist in the case an old infolist is used to the new format. The dots in the names are not good, but a result of an old school `read.csv()` or a wrong use of it (as @sneumann mentioned). Now is the time to change it.

**Comment by tsufz** [comment]
> 

According to my suggestion, the internal infofile handling is forward compatible now. Old lists are transformed to the new field format (no `.`, but `_`. And the spooky first column is removed (as an artefact of an incorrect use of `write.csv`.)

**Comment by tsufz** [comment]
This makes gatherCCTS more flexible and uses the full capacity of data retrieved.

**Comment by meowcat** [comment]
Sorry for the delay. I'm trying to go through this. Right now there is an issue with getDTXCID because it needs the API key... Do we simply omit testing this?

**Comment by tsufz** [comment]
> Sorry for the delay. I'm trying to go through this. Right now there is an issue with getDTXCID because it needs the API key... Do we simply omit testing this?

@meowcat, yes, all the CCTE requests require the API key. However, very useful to get DTXCID/DTXSID and the recent CASNR as they maintain it.

**Comment by tsufz** [comment]
@meowcat, how to edit the code to remove the checks? Just deleting the run chunk?

**Comment by meowcat** [comment]
@tsufz, sent a PR to your dev branch that `\dontrun{}`s the CCTE code

**Comment by meowcat** [comment]
OK, went through it. Nice work
I added one more fix to the workflow (in the PR to your dev branch) to skip the CCTE lookup if no API key is present. Then let's look if the CI goes through...

**Comment by meowcat** [comment]
A comment, I saw that we now use both httr and httr2, that seems unnecessary. Doesn't need solving today but should eventually be evened out

**Review by meowcat — APPROVED** [review]
I reviewed offline because github doesn't diff nicely. As in the PR thread, I just want to see the checks go through

**Comment by tsufz** [comment]
> A comment, I saw that we now use both httr and httr2, that seems unnecessary. Doesn't need solving today but should eventually be evened out

I agree, but needs some reformatting. I will add an issue and make a note in the wiki for the coding practise.

**Comment by meowcat** [comment]
We're getting closer: 
https://github.com/MassBank/RMassBank/actions/runs/5997364100/job/16263609142?pr=342#step:21:73

**Comment by tsufz** [comment]
@meowcat, I dunno what is still the issue. Your fix was properly merged in my fork...

**Comment by meowcat** [comment]
All is fine now, right?

**Pull request merged**
