### PR TITLE
Please review our pull request

### PR DESCRIPTION
**Pull request by sneumann**
Hi Michele, 
this is the pull request, still unchecked, will look at it 
after the Skype chat with Emma.

Yours,
Steffen

### CODE REVIEW

**Comment by sneumann** [comment]
Hi Michele, so after the Skype I went quickly over all commits and individual changes, 
and they look good to me. Emma also already tested this version in the last days on some data. 
So, let the pull begin! Yours, Steffen

**Comment by meowcat** [comment]
@sneumann @schymane @ermueller I just pushed to Bioc. Let's see what happens? :)

**Comment by ermueller** [comment]
Please inform me immediately when the next build report is up :) Is there a schedule for these?

**Comment by schymane** [comment]
they should be daily, iirc at 12:00 (midday?) Seattle time.
If you are lucky it'll happen today, if not, tomorrow.
Release is only built weekly, I think. You can read it up on the BioC website if you follow the links to developers pages.
Thanks for your efforts!

**Comment by schymane** [comment]
Thanks Michele and all, we've passed the build report ;)
________________________________________

**Pull request merged**
